# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-awesome_set}
  s.version = "0.11.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Nicoll", "David Haslem", "Martin Gamsjaeger (snusnu)"]
  s.date = %q{2010-04-12}
  s.description = %q{A library that lets any datamapper model act like a nested set}
  s.email = %q{jnicoll@gnexp.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "dm-is-awesome_set.gemspec",
     "lib/dm-is-awesome_set.rb",
     "spec/dm-is-awesome_set_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/changelog.rake",
     "tasks/ci.rake",
     "tasks/metrics.rake",
     "tasks/spec.rake",
     "tasks/yard.rake",
     "tasks/yardstick.rake"
  ]
  s.homepage = %q{http://github.com/snusnu/dm-is-awesome_set}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A nested set plugin for datamapper}
  s.test_files = [
    "spec/dm-is-awesome_set_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-adjust>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_development_dependency(%q<rspec>, ["~> 1.2.9"])
    else
      s.add_dependency(%q<dm-core>, ["~> 0.10"])
      s.add_dependency(%q<dm-adjust>, ["~> 0.10"])
      s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_dependency(%q<rspec>, ["~> 1.2.9"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 0.10"])
    s.add_dependency(%q<dm-adjust>, ["~> 0.10"])
    s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
    s.add_dependency(%q<rspec>, ["~> 1.2.9"])
  end
end

